pipeline:
  jsunit:
    image: nextcloudci/jsunit:1.0.6
    commands:
      - ./autotest-js.sh
    when:
      matrix:
        TESTS: jsunit
  nodb-php5.4:
    image: nextcloudci/php5.4:1.0.7
    commands:
      - git submodule update --init
      - NOCOVERAGE=true TEST_SELECTION=NODB ./autotest.sh sqlite
    when:
      matrix:
        DB: NODB
        PHP: 5.4
  nodb-php5.5:
    image: nextcloudci/php5.5:1.0.7
    commands:
      - git submodule update --init
      - NOCOVERAGE=true TEST_SELECTION=NODB ./autotest.sh sqlite
    when:
      matrix:
        DB: NODB
        PHP: 5.5
  nodb-php5.6:
    image: nextcloudci/php5.6:1.0.6
    commands:
      - git submodule update --init
      - NOCOVERAGE=true TEST_SELECTION=NODB ./autotest.sh sqlite
    when:
      matrix:
        DB: NODB
        PHP: 5.6
  nodb-php7.0:
    image: nextcloudci/php7.0:1.0.9
    commands:
      - git submodule update --init
      - NOCOVERAGE=true TEST_SELECTION=NODB ./autotest.sh sqlite
    when:
      matrix:
        DB: NODB
        PHP: "7.0"
  sqlite-php5.4:
    image: nextcloudci/php5.4:1.0.7
    commands:
      - git submodule update --init
      - NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh sqlite
    when:
      matrix:
        DB: sqlite
        PHP: 5.4
  sqlite-php5.5:
    image: nextcloudci/php5.5:1.0.7
    commands:
      - git submodule update --init
      - NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh sqlite
    when:
      matrix:
        DB: sqlite
        PHP: 5.5
  sqlite-php5.6:
    image: nextcloudci/php5.6:1.0.6
    commands:
      - git submodule update --init
      - NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh sqlite
    when:
      matrix:
        DB: sqlite
        PHP: 5.6
  sqlite-php7.0:
    image: nextcloudci/php7.0:1.0.9
    commands:
      - git submodule update --init
      - NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh sqlite
    when:
      matrix:
        DB: sqlite
        PHP: "7.0"
  mysql-php5.6:
    image: nextcloudci/php5.6:1.0.6
    commands:
      - sleep 15 # gives the database enough time to initialize
      - git submodule update --init
      - NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh mysql
    when:
      matrix:
        DB: mysql
        PHP: 5.6
  postgres-php5.6:
    image: nextcloudci/php5.6:1.0.6
    commands:
      - sleep 10 # gives the database enough time to initialize
      - git submodule update --init
      - NOCOVERAGE=true TEST_SELECTION=DB ./autotest.sh pgsql
    when:
      matrix:
        DB: postgres
        PHP: 5.6
  integration:
    image: nextcloudci/php7.0:1.0.9
    commands:
      - git submodule update --init
      - ./occ maintenance:install --admin-pass=admin
      - cd build/integration
      - ./run.sh
    when:
      matrix:
        TESTS: integration



matrix:
  include:
    - TESTS: integration
    - TESTS: jsunit
    - DB: NODB
      PHP: 5.4
    - DB: NODB
      PHP: 5.5
    - DB: NODB
      PHP: 5.6
    - DB: NODB
      PHP: 7.0
    - DB: sqlite
      PHP: 5.4
    - DB: sqlite
      PHP: 5.5
    - DB: sqlite
      PHP: 5.6
    - DB: sqlite
      PHP: 7.0
    - DB: mysql
      PHP: 5.6
    - DB: postgres
      PHP: 5.6

services:
  cache:
    image: redis
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=oc_autotest
      - POSTGRES_PASSWORD=oc_autotest
    when:
      matrix:
        DB: postgres
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=owncloud
      - MYSQL_USER=oc_autotest
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=oc_autotest
    when:
      matrix:
        DB: mysql
