pipeline:
  clone:
    image: plugins/git
    depth: 1
  jsunit:
    image: nextcloudci/jsunit:1.0.6
    commands:
      - ./autotest-js.sh
    when:
      matrix:
        TESTS: jsunit
  sqlite-php5.4:
    image: nextcloudci/php5.4:1.0.7
    commands:
      - ./occ maintenance:install --database-name oc_autotest --database-user oc_autotest --admin-user admin --admin-pass admin --database sqlite --database-pass=''
      - NOCOVERAGE=true ./autotest.sh sqlite
    when:
      matrix:
        DB: sqlite
        PHP: 5.4
  sqlite-php5.5:
    image: nextcloudci/php5.5:1.0.7
    commands:
      - ./occ maintenance:install --database-name oc_autotest --database-user oc_autotest --admin-user admin --admin-pass admin --database sqlite --database-pass=''
      - NOCOVERAGE=true ./autotest.sh sqlite
    when:
      matrix:
        DB: sqlite
        PHP: 5.5
  sqlite:
    image: nextcloudci/php5.6:1.0.6
    commands:
      - ./occ maintenance:install --database-name oc_autotest --database-user oc_autotest --admin-user admin --admin-pass admin --database sqlite --database-pass=''
      - ./autotest.sh sqlite
    when:
      matrix:
        DB: sqlite
        PHP: 5.6
  postgres:
    image: nextcloudci/php5.6:1.0.6
    commands:
      - sleep 10 # gives the database enough time to initialize
      - ./autotest.sh pgsql
    when:
      matrix:
        DB: postgres
        PHP: 5.6
  integration:
    image: nextcloudci/php5.6:1.0.6
    commands:
      - ./occ maintenance:install --admin-pass=admin
      - cd build/integration
      - ./run.sh
    when:
      matrix:
        TESTS: integration

matrix:
  include:
    - TESTS: integration
    - TESTS: jsunit
    - DB: sqlite
      PHP: 5.4
    - DB: sqlite
      PHP: 5.5
    - DB: sqlite
      PHP: 5.6
    - DB: postgres
      PHP: 5.6

services:
  cache:
    image: redis
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=oc_autotest
      - POSTGRES_PASSWORD=oc_autotest
    when:
      matrix:
        DB: postgres
